---
language: node_js
node_js:
  - "6"

sudo: false

env:
  global:
  - COVERAGE=true
  - CODECLIMATE_REPO_TOKEN=f8dc665e9c00b1004c7096875601a3bb39b6b8afd640ca63bca0255068403d35

addons:
  code_climate:
    repo_token: f8dc665e9c00b1004c7096875601a3bb39b6b8afd640ca63bca0255068403d35

cache:
  directories:
  - "$HOME/.yarn"

before_install:
  - yarn global add bower codeclimate-test-reporter phantomjs-prebuilt

install:
  - yarn install

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

script:
  - yarn test
