---
language: node_js
node_js:
  - "6"

sudo: false

addons:
  code_climate:
    repo_token: f8dc665e9c00b1004c7096875601a3bb39b6b8afd640ca63bca0255068403d35

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
